// @ts-check
import { defineConfig } from 'astro/config';

import sitemap from '@astrojs/sitemap';
import pagefind from 'astro-pagefind';

/**
 * @see https://astro.build/config
 */
export default defineConfig({
  /**
   * Defines the canonical URL for the project.
   * Required for sitemap and other SEO integrations.
   */
  site: 'https://devfolio.pl',

  integrations: [sitemap(), pagefind()],

  markdown: {
    shikiConfig: {
      theme: 'dracula',
    },
  },

  vite: {
    css: {
      preprocessorOptions: {
        scss: {
          // Suppresses `@use` warnings from dependencies, cleaning up build logs.
          quietDeps: true,
        },
      },
    },
    build: {
      rollupOptions: {
        /**
         * Prevents Vite from bundling the Pagefind script. This is critical because
         * the script is generated by the Pagefind integration *after* Vite's
         * bundling analysis, and it must be loaded as a separate static asset.
         */
        external: ['/pagefind/pagefind.js'],
      },
    },
  },
});
