// file: astro.config.mjs
// @ts-check
import { defineConfig } from 'astro/config';

import sitemap from '@astrojs/sitemap';
import pagefind from 'astro-pagefind';

import path from 'node:path';

/**
 * @see https://astro.build/config
 */
export default defineConfig({
  /**
   * Defines the canonical URL for the project.
   * Required for sitemap and other SEO integrations.
   */
  site: 'https://devfolio.pl',

  prefetch: {
    prefetchAll: true,
    defaultStrategy: 'viewport',
  },

  integrations: [sitemap(), pagefind()],

  markdown: {
    shikiConfig: {
      theme: 'dracula',
    },
  },

  vite: {
    css: {
      preprocessorOptions: {
        scss: {
          // Suppresses `@use` warnings from dependencies, cleaning up build logs.
          quietDeps: true,
        },
      },
    },
    build: {
      rollupOptions: {
        /**
         * Prevents Vite from bundling the Pagefind script. This is critical because
         * the script is generated by the Pagefind integration *after* Vite's
         * bundling analysis, and it must be loaded as a separate static asset.
         */
        external: ['/pagefind/pagefind.js'],
      },
    },
    server: {
      fs: {
        allow: [
          process.cwd(),
          path.resolve(process.cwd(), './src/content/blog'),
        ],
      },
      watch: {
        ignored: ['**/*.crswap', '**/*.(jpeg|jpg|png|gif|svg|webp|avif)'],
      },
    },
  },
});
