# --- Build Configuration ---
# Tells Netlify how to build our Astro site.
[build]
command = "bun run build"
publish = "dist"


# --- Security Headers ---
# Apply the following security headers to all pages (`/*`).
[[headers]]
for = "/*"
[headers.values]

# === Core Security Headers ===

# Prevents clickjacking; blocks site from being used in `<iframe>`s.
X-Frame-Options = "DENY"
# Prevents MIME-sniffing; ensures browser respects file types.
X-Content-Type-Options = "nosniff"
# Enhances privacy by controlling referrer data sent to other sites.
Referrer-Policy = "strict-origin-when-cross-origin"
# Disables access to sensitive browser APIs (camera, microphone, etc.).
Permissions-Policy = "camera=(), microphone=(), geolocation=(), payment=(), usb=()"

# === Advanced Cross-Origin Headers (Optional but Recommended) ===
# Prevents other domains from loading our resources (e.g., images).
Cross-Origin-Resource-Policy = "same-origin"
# Isolates our site from pop-ups to mitigate certain attacks.
Cross-Origin-Opener-Policy = "same-origin"

# === HSTS (HTTP Strict Transport Security) ===

# Enforces HTTPS connections to prevent man-in-the-middle attacks.
Strict-Transport-Security = "max-age=63072000; includeSubDomains; preload"


# === Content Security Policy (CSP) ===

# Your site's firewall. Defines a whitelist of allowed sources to prevent XSS attacks.
#
# DEBUGGING TIP: If something breaks (images, scripts), check the browser console (F12).
# "CSP" errors will tell you exactly which domain to add to the list below.
Content-Security-Policy = """
      default-src 'self';
      script-src 'self' 'unsafe-inline' 'wasm-unsafe-eval' 'unsafe-eval' static.cloudflareinsights.com giscus.app https://unpkg.com data:;
      style-src 'self' 'unsafe-inline' giscus.app https://fonts.googleapis.com;
      img-src 'self' data: blob: avatars.githubusercontent.com placehold.co raw.githubusercontent.com;
      connect-src 'self' cloudflare.com api.github.com cloudflareinsights.com https://unpkg.com https://www.githubstatus.com;
      frame-src giscus.app;
      font-src 'self' data: https://fonts.gstatic.com;
      object-src 'none';
      form-action 'self';
      frame-ancestors 'none';
    """
# ===================================================================
# === SECTION OF AGGRESSIVE CACHING ===
# ===================================================================

# Assets that are versioned (i.e., their URLs change when their content changes)
# can be cached aggressively for better performance and reduced bandwidth.
[[headers]]
for = "/_astro/*"
[headers.values]
Cache-Control = "public, max-age=31536000, immutable"

# 2. Images im tje public folder.
[[headers]]
for = "/images/*"
[headers.values]
Cache-Control = "public, max-age=31536000, immutable"

# 3. Fonts in the public folder.
[[headers]]
for = "/fonts/*"
[headers.values]
Cache-Control = "public, max-age=31536000, immutable"


# --- Headers for HTML files (to ensure changes are always visible) ---
[[headers]]
for = "/*.html"
[headers.values]
# "public" - can be cached by CDN.
# "max-age=0" - the browser must immediately consider its version stale.
# "must-revalidate" - the browser MUST check with the server if a new version exists before using the cached copy.
Cache-Control = "public, max-age=0, must-revalidate"

# --- SPA / Client Router fallback for Astro ---
[[redirects]]
from = "/*"
to = "/index.html"
status = 200
