# yaml-language-server: $schema=https://unpkg.com/@sveltia/cms/schema/sveltia-cms.json
# File: public/admin/config.yml

# Backend configuration for Sveltia CMS (using direct GitHub connection)
backend:
  name: github
  repo: n1ghtmare13/portfolio-blog-projekt # Your GitHub repository
  branch: main # The branch where content changes will be saved

# Where the CMS should look for and save media files
media_folder: "src/content/blog"
public_folder: ""

# Definition of your content collections (currently just the blog)
collections:
  - name: "blog" # This must match the collection name in src/content/config.ts
    label: "Blog Posts" # How the collection is named in the CMS UI
    folder: "src/content/blog" # Where to save new .md files
    create: true # Allow creating new entries
    slug: "{{fields.slug_override | default('{{title}}')}}" # How slugs are generated
    media_folder: "{{slug}}"
    public_folder: "./{{slug}}"
    fields: # The fields that will appear in the editor
      - { label: "Title", name: "title", widget: "string" }
      - {
          label: "Custom URL Slug (Optional)",
          name: "slug_override",
          widget: "string",
          required: false, # This field is optional
          hint: "Jeśli zostawisz puste, URL zostanie wygenerowany z tytułu. Wpisz własny, aby go nadpisać (np. 'moj-wlasny-slug').",
        }
      - { label: "Publish Date", name: "pubDate", widget: "datetime" }
      - { label: "Description", name: "description", widget: "string" }
      - { label: "Cover Image", name: "coverImage", widget: "image" }
      - { label: "Image Alt Text", name: "coverAlt", widget: "string" }
      - { label: "Body", name: "body", widget: "markdown" }
